import vertexai
from vertexai.preview import reasoning_engines
from vertexai.generative_models import GenerativeModel, Part

PROJECT_ID = "gcp-wow-wwnz-edr-reactpoc-test"
LOCATION = "us-central1"
# CRITICAL: This must be the numeric ID (e.g., "461...") from the Google Cloud Console
AGENT_ID = "agent_1778658051045" 

# Initialize Vertex AI before calling the Reasoning Engine
vertexai.init(project=PROJECT_ID, location=LOCATION)

AGENT_RESOURCE_NAME = f"projects/{PROJECT_ID}/locations/{LOCATION}/reasoningEngines/{AGENT_ID}"

# Define agent globally
try:
    agent = reasoning_engines.ReasoningEngine(AGENT_RESOURCE_NAME)
    print("Agent initialized successfully.")
except Exception as e:
    agent = None
    print(f"Failed to initialize agent: {e}")

def get_vertex_outputs(mongo_data):
    """
    Passes the full MongoDB record as a JSON payload to the Vertex Agent.
    The agent handles prompt logic and returns the image URL.
    """
    try:
        # We send the entire dictionary to the agent.
        # The agent 'test_ag' will receive this as its 'input'
        response = agent.query(input=mongo_data)

        # Assuming the agent returns a dictionary containing 'image_url' 
        # and potentially 'shelf_talker_copy'
        return {
            "ai_image_url": response.get("image_url"),
            "shelf_talker_copy": response.get("shelf_talker_copy", "Generated by Agent"),
            "status": "success"
        }
        
    except Exception as e:
        return {"error": f"Agent call failed: {str(e)}"}
        
def verify_promotion_compliance(image_bytes, promo_data):
    """
    Acts as the 'Localised Compliance Auditor'.
    Still uses the standard Gemini Flash model for direct visual analysis.
    """
    model = GenerativeModel("gemini-1.5-flash-002")
    
    expected_price = promo_data.get('price', 'N/A')
    expected_start = promo_data.get('start_date', 'N/A')
    expected_end = promo_data.get('end_date', 'N/A')
    p_type = promo_data.get('promotion_type', 'Standard')

    prompt = f"""
    Act as a Retail Compliance Auditor. 
    Compare the text and details in this promotional image against the following official data:
    - Promotion Type: {p_type}
    - Expected Price: {expected_price}
    - Start Date: {expected_start}
    - End Date: {expected_end}

    Task:
    1. Check if the price shown in the image matches the Expected Price.
    2. Verify the start and end dates are clearly visible and correct.
    3. Ensure the branding (e.g., "Price Promise") matches the Promotion Type.
    
    Return a JSON response with:
    "status": "APPROVED" or "REJECTED",
    "reason": "Explanation of findings"
    """

    # Create the image part
    image_part = Part.from_data(data=image_bytes, mime_type="image/jpeg")

    try:
        # Call Vertex AI with both text and image parts
        response = model.generate_content([image_part, prompt])
        return response.text
    except Exception as e:
        return {"error": f"Compliance check failed: {str(e)}"}